# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Crustal Deformation @ IU
email: kajjohns@iu.edu
description: We are researching crustal tectonics with a focus on...

# dont use this for github io hosting
# remote_theme: "jekyll/minima@1e8a445"

sass:
  quiet_deps: true
# >- # this means to ignore newlines

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kajjohns

# Build settings
theme: minima
plugins:
  - jekyll-feed
collections:
  pubs:
    output: true
    permalink: /recent_publications/:title/
    
  people:
    output: true
    permalink: /people/:title/
    
  codes:
    output: true
    permalink: /codes/:title/
    
# these lines allow the website to use Latex for math
kramdown:
  input: GFM
  math: true
